name: RevivePlugin
version: @version@
main: net.kunmc.lab.reviveplugin.RevivePlugin
api-version: 1.15
authors: [ Yu_212 ]
commands:
  reviveconfig:
    usage: /reviveconfig <set|reload> <value>
depend: [ "ProtocolLib" ]
