name: RevivePlugin
version: @version@
main: net.kunmc.lab.reviveplugin.RevivePlugin
api-version: 1.15
authors: [ Yu_212 ]
permissions:
  revive.configcommand:
    default: op
commands:
  reviveconfig:
    usage: /reviveconfig <set|reload> <value>
    permission: revive.configcommand
depend: [ "ProtocolLib" ]
