name: RevivePlugin
version: @version@
main: net.kunmc.lab.reviveplugin.RevivePlugin
api-version: 1.15
authors: [ Yu_212 ]
commands:
  reviveconfig:
    description: Revive Pluginのコンフィグ設定コマンドです
    usage: /reviveconfig <set|reload> <value>
    permission: revive.configcommand
permissions:
  revive.configcommand:
depend: [ "ProtocolLib" ]
